#!/bin/bash

nasm -fbin loader.s -o loader.bin
dd status=noxfer conv=notrunc if=loader.bin of=os.flp
nasm -fbin kernel.s -o kernel.bin 
dd seek=1 count=1 status=noxfer conv=notrunc if=kernel.bin of=os.flp
qemu-system-i386 -fda os.flp
