#!/bin/bash

nasm -fbin loader.s -o LOADER.BIN
dd status=noxfer  conv=notrunc if=LOADER.BIN of=os.img
nasm -fbin kernel.s -o KERNEL.BIN
dd status=noxfer  conv=notrunc  count=1 seek=1 if=KERNEL.BIN of=os.img
qemu-system-i386 -fda os.img
