#!/bin/bash

nasm -fbin loader.s -o loader.bin
dd bs=512 conv=notrunc if=loader.bin of=os.flp
nasm -fbin kernel.s -o kernel.bin
dd bs=512  seek=1  conv=notrunc if=kernel.bin of=os.flp
qemu-system-i386 -fda os.flp
